from .test_method_based import TestMethodBased
from .test_attribute_based import TestAttributeBased
from .test_meta_object import TestMetaObject
from .test_map_optimization import TestMapOptimization
